# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', django_unixdatetimefield.fields.UnixDateTimeField()),
            ],
        ),
    ]
